# Generated by Django 4.1.7 on 2023-04-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('isSelected', models.BooleanField(default=False)),
            ],
        ),
    ]
